name: 'Tofu'

on:
  push:
#     branches:
#     - main
#   pull_request:
#     branches:
#     - main


permissions:
  contents: read
  pull-requests: write
   
jobs:
  plan:
    name: 'Tofu Plan'
    runs-on: ubuntu-latest
    outputs:
      tfplanExitCode: ${{ steps.plan.outputs.tf_exitcode }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.8.0


    - name: OpenTofu Plan
      id: plan
      run: |
        tofu init
        tofu plan -detailed-exitcode -input=false -no-color -out plan.tfplan
        # case $(tofu plan -detailed-exitcode -input=false -no-color -out plan.tfplan) in
        #   0) export tf_exitcode=0 && echo "No changes detected" ;;
        #   2) export tf_exitcode=2 && echo "Changes detected" ;;
        #   *) export tf_exitcode=1 && echo "Error running plan" ;;
        # esac
        
        echo "tf_exitcode=$tf_exitcode" >> "$GITHUB_OUTPUT"

        # echo "~~~ $(tofu show -no-color ./plan.tfplan) ~~~" >> $GITHUB_STEP_SUMMARY
        # echo "plan<<EOF" >> $GITHUB_OUTPUT
        # echo "$(tofu show -no-color ./plan.tfplan)" >> "$GITHUB_OUTPUT"
        # echo "EOF" >> $GITHUB_OUTPUT

        if [[ $tf_exitcode -eq 2 ]]; then
          echo "ADD_TO_PR=true" >> "$GITHUB_ENV"
          exit 0
        elif [[ $tf_exitcode -eq 0 ]]; then
          exit 0
        else
          exit $tf_exitcode
        fi

    - name: Upload Plan
      id: upload-plan
      if: (steps.plan.outputs.tf_exitcode == 2)
      uses: actions/upload-artifact@v4
      with:
        name: TofuPlan
        path: plan.tfplan

    - name: Post plan to PR
      if: ${{ (steps.plan.outputs.tf_exitcode == 2) && (github.event_name == 'pull_request') && (env.ADD_TO_PR == 'true') }}
      uses: actions/github-script@v7
      env:
        PLAN: ${{ steps.plan.outputs.plan }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `### Planned changes in this PR

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`

          </details>

          `;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

  apply:
    name: Tofu Apply
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/main' && needs.plan.outputs.tfplanExitCode == 2)
    needs: [plan]
    environment:
      name: tf-apply
    steps:
      - uses: actions/checkout@v4

      - name: Download Tofu plan
        uses: actions/download-artifact@v4
        with:
          name: TofuPlan
          path: plan.tfplan

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.8.0

      - name: Tofu Apply
        run: |
          set -o pipefail
          tofu init
          tofu apply -input=false -no-color plan.tfplan/plan.tfplan | tee apply.txt
          export tf_exitcode=$?
          echo "tf_exitcode=$tf_exitcode" >> $GITHUB_OUTPUT

          if [[ $tf_exitcode -eq 0 ]]; then
            exit 0
          else
            exit $tf_exitcode
          fi

      - name: Output Apply Results to Summary
        run: |
          echo "~~~ $(cat apply.txt) ~~~" >> $GITHUB_STEP_SUMMARY